name: CI-STAGING

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/main:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/main:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/main:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/main:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/main:${{ github.sha }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-action-cmd.pem
          chmod 400 ~/.ssh/github-action-cmd.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-action-cmd.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/main:${{ github.sha }}
            docker stop main || true  
            docker rm main || true   
            docker run -d --name main -p 8088:8088 ${{ secrets.DOCKER_HUB_USERNAME }}/main:${{ github.sha }}
          "
