name: CI-STAGING

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t username/dbdemo:${{ github.sha }} .
          docker tag username/dbdemo:${{ github.sha }} username/dbdemo:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub #推送到Docker Hub
        run: |
          docker push username/dbdemo:latest
          docker push username/dbdemo:${{ github.sha }}

      - name: Deploy to server #部署到服务器
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull username/dbdemo:${{ github.sha }}
            docker stop dbdemo || true  
            docker rm dbdemo || true   
            docker run -d --name dbdemo -p 3000:3000 username/dbdemo:${{ github.sha }}
